### ISSUE TITLE
Status of this repo

### ISSUE THREAD

**Issue by Swader** [status-im/nim-confutils#1]
@zah would you mind please clarifying the purpose of this repo in a small README? I can add the LICENSE info in there too, i.e. link to the files in the repo.

**Comment by zah** [comment]
I've added a README that's ready for review. For now, large parts of the provided spec are not implemented and we might decide to clarify this, but I'm not sure we can justify spending time on this.

Closed in 531b4033378447dc4f196f6fbf040a197f7be307
