### ISSUE TITLE
Error: newLitFixed cmdInfo can raise an unlisted exception: Exception

### ISSUE THREAD

**Issue by matthiaswh** [status-im/nim-confutils#106]
> /home/matthias/.nimble/pkgs2/confutils-0.1.0-1f21a103798b7f550db123459801ecf05b2d8ed7/confutils.nim(862, 1) template/generic instantiation from here
> /home/matthias/.nimble/pkgs2/confutils-0.1.0-1f21a103798b7f550db123459801ecf05b2d8ed7/confutils.nim(868, 40) Error: newLitFixed cmdInfo can raise an unlisted exception: Exception

This is not related to my code, but happens with only a `import confutils` statement.

Nim version (though I tried on devel also with the same failure).
```
Nim Compiler Version 2.0.6 [Linux: amd64]
Compiled at 2024-06-17
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c00e8e71e0c8465b5a5257c76c674b803273b222
active boot switches: -d:release
```

It works on 1.6.

**Comment by 2-towns** [comment]
I had the same problem, and it went away when I updated nim-stew.

**Comment by jangko** [comment]
closing due to not this library problem but nim-stew.
