### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-confutils#2]
Currently, when an option is wrong somehow, all you get is a useless call stack:
```
confutils.nim(131)       beacon_node
confutils.nim(296)       load
confutils.nim(108)       validatorsSetter
conf.nim(93)             parseCmdArg
Error: unhandled exception:  [ValueError]
```

with no hint as to what's wrong (file missing? couldn't parse? no idea)

**Comment by zah** [comment]
Error messages have been significantly improved since this bug report.
