### ISSUE TITLE
Weird "`static type` is not a concrete type"

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-confutils#3]
While refactoring https://github.com/status-im/nim-beacon-chain/blob/3575e3842e0837667421526e239d7a6619f6fb1c/research/serialized_sizes.nim#L7-L29, I tried to use static bool. Well obviously confutils is runtime configuration file so it wouldn't work but the error message is very strange.

Minimal reproduction code:

```Nim
import confutils

proc foo(a: int, b: static bool = false) =
  discard

dispatch(foo)
```

```
static_bool.nim(6, 9) template/generic instantiation from here
static_bool.nim(3, 18) Error: 'static[bool]' is not a concrete type
```

**Comment by zah** [comment]
I would say the message is quite clear. Using a `static` parameter makes the function generic, which is something that Confutils cannot support (the generic function cannot be instantiated at run-time).

I'm closing this issue with the following improvements to the docs:
https://github.com/status-im/nim-confutils/commit/71643c914110f4549884abd75f22586ee675d98d
71643c914110f4549884abd75f22586ee675d98d
