### ISSUE TITLE
Regression on beacon chain simulation

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-confutils#4]
This commits breaks the beacon chain simulation: https://github.com/status-im/nim-confutils/commit/7c0a19416eb03457d6156665552531ded009055a

![DeepinScreenshot_select-area_20190326083856](https://user-images.githubusercontent.com/22738317/54981800-83c05c80-4fa9-11e9-8372-aa4a0fc93124.png)

**Comment by zah** [comment]
Fixed in 510a8835942ec7ca27f42f4f796debca38bf743c
