### ISSUE TITLE
Support for nimscript?

### ISSUE THREAD

**Issue by kdeme** [status-im/nim-confutils#7]
1. Current version will not allow to run nimscript with confutils at all due to: 
```/nix/store/20vz8aa4cw99b33f2vgvc69iy39nxr7p-nim-0.19.6/lib/pure/streams.nim(100, 7) Error: undeclared identifier: 'copyMem'```

2. When using revision 14da5a0077f8dcbdc11f80cf855955506b1051e6 with commit 9224d1feaf42f176a406c79a5514253eff66c4ab on top (basically skipping https://github.com/status-im/nim-confutils/pull/5) you can import and use confutils, however I noticed following wrong behaviour running this example code:

```nim
import confutils

type
  Foo* = enum
    foo1
    foo2

  Bar* = enum
    bar1
    bar2

  TestConf* = object
    foo* {.
      desc: "FOO",
      longform: "foo",
      defaultValue: foo1.}: Foo

    bar* {.
      desc: "BAR",
      longform: "bar",
      defaultValue: bar1.}: Bar

let conf = TestConf.load()
```

When in `test.nim` and running `nim c -r test.nim --foo=foo1 --bar=bar2`, it works.

When in `test.nims` and running `nim test.nims --foo=foo1 --bar=bar2`, it fails with:
```
Unrecognized option 'foobar'
Try 'nim test.nims --help' for more information
```

Using only 1 option works: ```nim test.nims --foo=foo1```

**Comment by zah** [comment]
The NimScript support was restored in aa5ccdd57fe25aa0d10b770ae8e8fdafba6bbbb4
